---
-
  hosts: localhost

  vars:
    base_image_name: ami-03cfb5e1fb4fac428
    instance_type: t2.micro
    number_of_instances_to_create: 1
    region: ap-south-1
    ssh_host_key_checking: False

  tasks:

    - name: Delete existing password file
      file:
        path: ./jenkinsPassword.txt
        state: absent

    - name: Delete existing password file
      file:
        path: ./jenkinsPassword.txt
        state: absent

    - name: Delete existing password file
      file:
        path: ./jenkinsPassword.txt
        state: absent

    - name: Delete existing password file
      file:
        path: ./jenkinsPassword.txt
        state: absent

    - name: Create a suitable set of firewall rules
      ec2_group:
         vpc_id: vpc-45ce2e2e
         name: jenkins_server_security_groups
         description: Specific rules for a Jenkins Instance
         region: "{{ region }}"
         rules_egress:
            - proto: tcp
              from_port: 0
              to_port: 65535
              cidr_ip: 0.0.0.0/0
         rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0

            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0

    -
      ec2:
        aws_access_key: AKIAW3YQQJHCALGMOK6K
        aws_secret_key: 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
        count_tag:
          Name: Jenkins_Server
        exact_count: "{{ number_of_instances_to_create }}"
        group: jenkins_server_security_groups
        image: "{{ base_image_name }}"
        instance_tags:
          Name: Jenkins_Server
        instance_type: "{{ instance_type }}"
        key_name: my-key
        region: "{{ region }}"
        vpc_subnet_id: subnet-f76a639f
        wait: true
      name: "Create a new EC2 instance"
      register: ec2
    -
      debug:
        var: ec2
    -
      add_host:
        groups: new_ec2_instances
        hostname: "{{ item.public_ip }}"
      name: "Gather the new ip addresses"
      with_items: "{{ ec2.tagged_instances }}"
    -
      name: "Wait for the SSH port to respond"
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22
        state: started
      with_items: "{{ ec2.tagged_instances }}"
-
  hosts: "new_ec2_instances, tag_Name_Jenkins_Server"
  tasks:
    -
      name: "Apply Patches"
      yum: "name=* state=latest"
    -
      debug: "msg=\"Yes, found the inventory\""
      name: "A dummy task to see if dynamic inventory is found"

    - name: Ensure Apache is NOT on this server.
      yum: name=httpd state=absent
      become: yes

    - name: Patch up the server
      yum: name=* state=latest
      become: yes

    - name: Install JDK
      yum:
         name: java-1.8.0-openjdk-devel
         state: latest
      become: true

    - name: Use Java8 for Runtime Java
      alternatives:
         name: java
         path: /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
         link: /usr/bin/java
      become: true

    - name: Add Jenkins Red Hat Repository
      yum_repository:
        name: jenkins
        description: Jenkins Repo
        baseurl: https://pkg.jenkins.io/redhat-stable
      become: yes

    - name: Add RPM Key
      rpm_key:
         key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
      become: yes

    - name: Install Jenkins
      yum:
         name: jenkins
         state: latest
      become: yes

    - name: Start up Jenkins
      service:
         name: jenkins
         state: started
         enabled: yes
      become: yes

    - name: Wait for Jenkins Start
      wait_for:
         port: 8080
         state: started
         delay: 30

    - name: Get Initial password
      fetch:
        src: /var/lib/jenkins/secrets/initialAdminPassword
        dest: ./jenkinsPassword.txt
        flat: yes
        fail_on_missing: no
      become: yes

    - name: Install Git
      yum: name=git state=latest
      become: yes

    - name: Prepare Maven Directory
      file:
         path: /opt
         state: directory
      become: true

    - name: Download Maven
      get_url:
         url: https://www.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
         dest: /opt/maven3.tar.gz
      become: true

    - name: Unpack Maven
      unarchive:
         remote_src: yes
         src: /opt/maven3.tar.gz
         dest: /opt/
      become: true

    - name: Set Mvn command
      alternatives:
         name: mvn
         path: /opt/apache-maven-3.3.9/bin/mvn
         link: /usr/bin/mvn
      become: true

    - name: Install Ansible
      pip:
         name: ansible
         extra_args: --no-cache-dir
      become: yes

    - name: Boto3
      pip:
         name: boto3
      become: yes
